import type { NetworkId, NetworkParams } from "./types";

export const NETWORKS: Record<NetworkId, NetworkParams> = {
  testnet: {
    id: "testnet",
    chainId: 2,
    name: "Equilibrium Testnet",
    domain: "equilibrium.site",
    targetBlockTimeMs: 8000,
    residualThreshold: 2e-3,
    territoryThreshold: 1e-7,
    initialDifficulty: 1_000_000,
    baseReward: 100,
    halvingInterval: 2_100_000,
    maxTxPerBlock: 50,
    mempoolCap: 500,
    finalityQuorum: 2 / 3,
    finalityLag: 2,
    allowFaucet: true,
    faucetAmount: 1_000_000,
  },
  mainnet: {
    id: "mainnet",
    chainId: 1,
    name: "Equilibrium Mainnet",
    domain: "equilibrium.site",
    targetBlockTimeMs: 15000,
    residualThreshold: 8e-4,
    territoryThreshold: 1e-7,
    initialDifficulty: 1_000_000,
    baseReward: 100,
    halvingInterval: 2_100_000,
    maxTxPerBlock: 50,
    mempoolCap: 500,
    finalityQuorum: 2 / 3,
    finalityLag: 2,
    allowFaucet: false,
    faucetAmount: 0,
  },
};
