/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as BlocksRouteImport } from './routes/blocks'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as DexRouteImport } from './routes/dex'
import { Route as ExperimentsRouteImport } from './routes/experiments'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoopRouteImport } from './routes/loop'
import { Route as MempoolRouteImport } from './routes/mempool'
import { Route as MeshRouteImport } from './routes/mesh'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as ProtocolRouteImport } from './routes/protocol'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as StateRouteImport } from './routes/state'
import { Route as ValidatorsRouteImport } from './routes/validators'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as AddressAddrRouteImport } from './routes/address.$addr'
import { Route as ApiLightRouteImport } from './routes/api.light'
import { Route as ApiRtcRouteImport } from './routes/api.rtc'
import { Route as BlocksHashRouteImport } from './routes/blocks.$hash'
import { Route as ProtocolIdRouteImport } from './routes/protocol.$id'
import { Route as TxHashRouteImport } from './routes/tx.$hash'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksRoute = BlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const DexRoute = DexRouteImport.update({
  id: '/dex',
  path: '/dex',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsRoute = ExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoopRoute = LoopRouteImport.update({
  id: '/loop',
  path: '/loop',
  getParentRoute: () => rootRouteImport,
} as any)
const MempoolRoute = MempoolRouteImport.update({
  id: '/mempool',
  path: '/mempool',
  getParentRoute: () => rootRouteImport,
} as any)
const MeshRoute = MeshRouteImport.update({
  id: '/mesh',
  path: '/mesh',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolRoute = ProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const StateRoute = StateRouteImport.update({
  id: '/state',
  path: '/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidatorsRoute = ValidatorsRouteImport.update({
  id: '/validators',
  path: '/validators',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressAddrRoute = AddressAddrRouteImport.update({
  id: '/address/$addr',
  path: '/address/$addr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLightRoute = ApiLightRouteImport.update({
  id: '/api/light',
  path: '/api/light',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksHashRoute = BlocksHashRouteImport.update({
  id: '/$hash',
  path: '/$hash',
  getParentRoute: () => BlocksRoute,
} as any)
const ProtocolIdRoute = ProtocolIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProtocolRoute,
} as any)
const TxHashRoute = TxHashRouteImport.update({
  id: '/tx/$hash',
  path: '/tx/$hash',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/blocks': typeof BlocksRouteWithChildren
  '/contracts': typeof ContractsRoute
  '/developers': typeof DevelopersRoute
  '/dex': typeof DexRoute
  '/experiments': typeof ExperimentsRoute
  '/explorer': typeof ExplorerRoute
  '/library': typeof LibraryRoute
  '/loop': typeof LoopRoute
  '/mempool': typeof MempoolRoute
  '/mesh': typeof MeshRoute
  '/mobile': typeof MobileRoute
  '/protocol': typeof ProtocolRouteWithChildren
  '/research': typeof ResearchRoute
  '/state': typeof StateRoute
  '/validators': typeof ValidatorsRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/address/$addr': typeof AddressAddrRoute
  '/api/light': typeof ApiLightRoute
  '/api/rtc': typeof ApiRtcRoute
  '/blocks/$hash': typeof BlocksHashRoute
  '/protocol/$id': typeof ProtocolIdRoute
  '/tx/$hash': typeof TxHashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/blocks': typeof BlocksRouteWithChildren
  '/contracts': typeof ContractsRoute
  '/developers': typeof DevelopersRoute
  '/dex': typeof DexRoute
  '/experiments': typeof ExperimentsRoute
  '/explorer': typeof ExplorerRoute
  '/library': typeof LibraryRoute
  '/loop': typeof LoopRoute
  '/mempool': typeof MempoolRoute
  '/mesh': typeof MeshRoute
  '/mobile': typeof MobileRoute
  '/protocol': typeof ProtocolRouteWithChildren
  '/research': typeof ResearchRoute
  '/state': typeof StateRoute
  '/validators': typeof ValidatorsRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/address/$addr': typeof AddressAddrRoute
  '/api/light': typeof ApiLightRoute
  '/api/rtc': typeof ApiRtcRoute
  '/blocks/$hash': typeof BlocksHashRoute
  '/protocol/$id': typeof ProtocolIdRoute
  '/tx/$hash': typeof TxHashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/blocks': typeof BlocksRouteWithChildren
  '/contracts': typeof ContractsRoute
  '/developers': typeof DevelopersRoute
  '/dex': typeof DexRoute
  '/experiments': typeof ExperimentsRoute
  '/explorer': typeof ExplorerRoute
  '/library': typeof LibraryRoute
  '/loop': typeof LoopRoute
  '/mempool': typeof MempoolRoute
  '/mesh': typeof MeshRoute
  '/mobile': typeof MobileRoute
  '/protocol': typeof ProtocolRouteWithChildren
  '/research': typeof ResearchRoute
  '/state': typeof StateRoute
  '/validators': typeof ValidatorsRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/address/$addr': typeof AddressAddrRoute
  '/api/light': typeof ApiLightRoute
  '/api/rtc': typeof ApiRtcRoute
  '/blocks/$hash': typeof BlocksHashRoute
  '/protocol/$id': typeof ProtocolIdRoute
  '/tx/$hash': typeof TxHashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/blocks'
    | '/contracts'
    | '/developers'
    | '/dex'
    | '/experiments'
    | '/explorer'
    | '/library'
    | '/loop'
    | '/mempool'
    | '/mesh'
    | '/mobile'
    | '/protocol'
    | '/research'
    | '/state'
    | '/validators'
    | '/verify'
    | '/wallet'
    | '/address/$addr'
    | '/api/light'
    | '/api/rtc'
    | '/blocks/$hash'
    | '/protocol/$id'
    | '/tx/$hash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/blocks'
    | '/contracts'
    | '/developers'
    | '/dex'
    | '/experiments'
    | '/explorer'
    | '/library'
    | '/loop'
    | '/mempool'
    | '/mesh'
    | '/mobile'
    | '/protocol'
    | '/research'
    | '/state'
    | '/validators'
    | '/verify'
    | '/wallet'
    | '/address/$addr'
    | '/api/light'
    | '/api/rtc'
    | '/blocks/$hash'
    | '/protocol/$id'
    | '/tx/$hash'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/blocks'
    | '/contracts'
    | '/developers'
    | '/dex'
    | '/experiments'
    | '/explorer'
    | '/library'
    | '/loop'
    | '/mempool'
    | '/mesh'
    | '/mobile'
    | '/protocol'
    | '/research'
    | '/state'
    | '/validators'
    | '/verify'
    | '/wallet'
    | '/address/$addr'
    | '/api/light'
    | '/api/rtc'
    | '/blocks/$hash'
    | '/protocol/$id'
    | '/tx/$hash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  BlocksRoute: typeof BlocksRouteWithChildren
  ContractsRoute: typeof ContractsRoute
  DevelopersRoute: typeof DevelopersRoute
  DexRoute: typeof DexRoute
  ExperimentsRoute: typeof ExperimentsRoute
  ExplorerRoute: typeof ExplorerRoute
  LibraryRoute: typeof LibraryRoute
  LoopRoute: typeof LoopRoute
  MempoolRoute: typeof MempoolRoute
  MeshRoute: typeof MeshRoute
  MobileRoute: typeof MobileRoute
  ProtocolRoute: typeof ProtocolRouteWithChildren
  ResearchRoute: typeof ResearchRoute
  StateRoute: typeof StateRoute
  ValidatorsRoute: typeof ValidatorsRoute
  VerifyRoute: typeof VerifyRoute
  WalletRoute: typeof WalletRoute
  AddressAddrRoute: typeof AddressAddrRoute
  ApiLightRoute: typeof ApiLightRoute
  ApiRtcRoute: typeof ApiRtcRoute
  TxHashRoute: typeof TxHashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks': {
      id: '/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof BlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dex': {
      id: '/dex'
      path: '/dex'
      fullPath: '/dex'
      preLoaderRoute: typeof DexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments': {
      id: '/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof ExperimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loop': {
      id: '/loop'
      path: '/loop'
      fullPath: '/loop'
      preLoaderRoute: typeof LoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mempool': {
      id: '/mempool'
      path: '/mempool'
      fullPath: '/mempool'
      preLoaderRoute: typeof MempoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesh': {
      id: '/mesh'
      path: '/mesh'
      fullPath: '/mesh'
      preLoaderRoute: typeof MeshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocol': {
      id: '/protocol'
      path: '/protocol'
      fullPath: '/protocol'
      preLoaderRoute: typeof ProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/state': {
      id: '/state'
      path: '/state'
      fullPath: '/state'
      preLoaderRoute: typeof StateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validators': {
      id: '/validators'
      path: '/validators'
      fullPath: '/validators'
      preLoaderRoute: typeof ValidatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/address/$addr': {
      id: '/address/$addr'
      path: '/address/$addr'
      fullPath: '/address/$addr'
      preLoaderRoute: typeof AddressAddrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/light': {
      id: '/api/light'
      path: '/api/light'
      fullPath: '/api/light'
      preLoaderRoute: typeof ApiLightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks/$hash': {
      id: '/blocks/$hash'
      path: '/$hash'
      fullPath: '/blocks/$hash'
      preLoaderRoute: typeof BlocksHashRouteImport
      parentRoute: typeof BlocksRoute
    }
    '/protocol/$id': {
      id: '/protocol/$id'
      path: '/$id'
      fullPath: '/protocol/$id'
      preLoaderRoute: typeof ProtocolIdRouteImport
      parentRoute: typeof ProtocolRoute
    }
    '/tx/$hash': {
      id: '/tx/$hash'
      path: '/tx/$hash'
      fullPath: '/tx/$hash'
      preLoaderRoute: typeof TxHashRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlocksRouteChildren {
  BlocksHashRoute: typeof BlocksHashRoute
}

const BlocksRouteChildren: BlocksRouteChildren = {
  BlocksHashRoute: BlocksHashRoute,
}

const BlocksRouteWithChildren =
  BlocksRoute._addFileChildren(BlocksRouteChildren)

interface ProtocolRouteChildren {
  ProtocolIdRoute: typeof ProtocolIdRoute
}

const ProtocolRouteChildren: ProtocolRouteChildren = {
  ProtocolIdRoute: ProtocolIdRoute,
}

const ProtocolRouteWithChildren = ProtocolRoute._addFileChildren(
  ProtocolRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  BlocksRoute: BlocksRouteWithChildren,
  ContractsRoute: ContractsRoute,
  DevelopersRoute: DevelopersRoute,
  DexRoute: DexRoute,
  ExperimentsRoute: ExperimentsRoute,
  ExplorerRoute: ExplorerRoute,
  LibraryRoute: LibraryRoute,
  LoopRoute: LoopRoute,
  MempoolRoute: MempoolRoute,
  MeshRoute: MeshRoute,
  MobileRoute: MobileRoute,
  ProtocolRoute: ProtocolRouteWithChildren,
  ResearchRoute: ResearchRoute,
  StateRoute: StateRoute,
  ValidatorsRoute: ValidatorsRoute,
  VerifyRoute: VerifyRoute,
  WalletRoute: WalletRoute,
  AddressAddrRoute: AddressAddrRoute,
  ApiLightRoute: ApiLightRoute,
  ApiRtcRoute: ApiRtcRoute,
  TxHashRoute: TxHashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
