plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace = "com.equilibrium"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.equilibrium.miner"
        minSdk = 26          // Android 8 — required for WorkManager foreground service
        targetSdk = 35
        versionCode = 1
        versionName = "0.1.0"
    }

    // ── Release signing ──────────────────────────────────────────────────────
    //
    // Wired to environment variables so CI (GitHub Actions) can sign release
    // APKs without a keystore file checked into source control:
    //   ANDROID_KEYSTORE_PATH      — absolute path to the decoded .p12/.jks file
    //   ANDROID_KEYSTORE_PASSWORD  — keystore password
    //   ANDROID_KEY_ALIAS          — key alias inside the keystore
    //   ANDROID_KEY_PASSWORD       — password for that specific key
    //
    // Locally, just leave these unset — `assembleDebug` doesn't need them, and
    // `assembleRelease` will fail fast with a clear Gradle error instead of
    // silently producing an unsigned/unusable APK.
    val ksPath = System.getenv("ANDROID_KEYSTORE_PATH")
    val ksPassword = System.getenv("ANDROID_KEYSTORE_PASSWORD")
    val ksKeyAlias = System.getenv("ANDROID_KEY_ALIAS")
    val ksKeyPassword = System.getenv("ANDROID_KEY_PASSWORD")
    val hasSigningEnv = !ksPath.isNullOrBlank() && !ksPassword.isNullOrBlank() &&
        !ksKeyAlias.isNullOrBlank() && !ksKeyPassword.isNullOrBlank()

    signingConfigs {
        if (hasSigningEnv) {
            create("release") {
                storeFile = file(ksPath!!)
                storePassword = ksPassword
                keyAlias = ksKeyAlias
                keyPassword = ksKeyPassword
                // The keystore generated by scripts/generate-keystore.sh is PKCS12;
                // Gradle infers this from the .p12 extension, but set it explicitly
                // in case the file is renamed.
                storeType = if (ksPath.endsWith(".p12")) "PKCS12" else "JKS"
            }
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            if (hasSigningEnv) {
                signingConfig = signingConfigs.getByName("release")
            }
            // else: unsigned release build — fine for local `assembleRelease`
            // smoke tests, but CI must set the ANDROID_KEYSTORE_* env vars.
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    // JNI libraries built by cargo-ndk go here:
    //   cargo ndk -t armeabi-v7a -t arm64-v8a -t x86_64 -o app/src/main/jniLibs build --release
    sourceSets["main"].jniLibs.srcDirs("src/main/jniLibs")
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.material)

    // WorkManager for battery-aware background mining
    implementation(libs.androidx.work.runtime.ktx)

    // HTTP client for submitting solved blocks to the node API
    implementation(libs.okhttp)
}

// ── cargo-ndk integration ─────────────────────────────────────────────────────
//
// Cross-compiles the Equilibrium Rust core for Android and drops the resulting
// .so files into src/main/jniLibs/ where the Android build system picks them up.
//
// Run manually:   ../build-jni.sh
// Gradle task:    ./gradlew cargoNdkBuild
//
// Prerequisites (see ../build-jni.sh for the full guide):
//   rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android
//   cargo install cargo-ndk
//   export ANDROID_NDK_HOME=/path/to/ndk
//
// To make every Gradle build trigger cargo-ndk automatically, uncomment the
// dependsOn line in the preBuild block below.

val cargoNdkBuild by tasks.registering(Exec::class) {
    description = "Cross-compile Rust core for Android via cargo-ndk"
    group = "build"
    workingDir = file("..") // equilibrium/mobile/android/
    commandLine("bash", "build-jni.sh")
    inputs.dir("${rootDir}/../../src")
    outputs.dir("src/main/jniLibs")
}

tasks.named("preBuild") {
    // Uncomment to wire cargo-ndk into every Gradle build automatically:
    // dependsOn(cargoNdkBuild)
}
