import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import chainRouter from "./chain.js";
import blocksRouter from "./blocks.js";
import transactionsRouter from "./transactions.js";
import addressesRouter from "./addresses.js";
import mempoolRouter from "./mempool.js";
import validatorsRouter from "./validators.js";
import dexRouter from "./dex.js";
import stakingRouter from "./staking.js";
import networkRouter from "./network.js";
import faucetRouter from "./faucet.js";
import utxoRouter from "./utxo.js";
import contractsRouter from "./contracts.js";
import evmRouter from "./evm.js";
import governanceRouter from "./governance.js";
import mobileRouter from "./mobile.js";
import adminRouter from "./admin.js";
import arbitrageRouter from "./arbitrage.js";
import modelsRouter from "./models.js";
import crossChainRelayRouter from "./crossChainRelay.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(chainRouter);
router.use(blocksRouter);
router.use(transactionsRouter);
router.use(addressesRouter);
router.use(mempoolRouter);
router.use(validatorsRouter);
router.use(dexRouter);
router.use(stakingRouter);
router.use(networkRouter);
router.use(faucetRouter);
router.use(utxoRouter);
router.use(contractsRouter);
router.use(evmRouter);
router.use(governanceRouter);
router.use(mobileRouter);
router.use(adminRouter);
router.use(arbitrageRouter);
router.use(modelsRouter);
router.use(crossChainRelayRouter);

export default router;
