// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  ".\u002Fcomponents\u002Fmockups\u002Fmatrix\u002FBlockChain3D.tsx": () => import("..\u002Fcomponents\u002Fmockups\u002Fmatrix\u002FBlockChain3D.tsx")
};
